### ISSUE TITLE
Error: Could not read temperature data

### ISSUE THREAD

**Issue by zKingFabzz** [jmchiappa/DallasTemperature#1]
Hello,
I have a DS18B20 temperature sensor and get only "Error: Could not read temperature data" as response. Could you say what I should try, please?

Best wishes
zKingFabzz

**Comment by jmchiappa** [comment]
Hello, without more information, no. Please elaborate what you're doing and using : 
- board model (nucleo, arduino, esp ?)
- pin connected to the ds18b20
- a part of your sketch
- a part of your schematic or at least a drawing (with pull up resistor and its value)

Thanks

**Comment by jmchiappa** [comment]
no more feedback. closed
